# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeviceMonitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from cloudstate import entity_key_pb2 as cloudstate_dot_entity__key__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import http_pb2 as google_dot_api_dot_http__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DeviceMonitor.proto',
  package='com.example.monitor',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x44\x65viceMonitor.proto\x12\x13\x63om.example.monitor\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1b\x63loudstate/entity_key.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"O\n\x0eNewMetricValue\x12\x17\n\tdevice_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x11\n\tnew_value\x18\x03 \x01(\x02\"0\n\x15GetCurrentMetricValue\x12\x17\n\tdevice_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\"\xbc\x01\n\x0bMetricValue\x12\x15\n\rcurrent_value\x18\x01 \x01(\x02\x12\x13\n\x0bprior_value\x18\x02 \x01(\x02\x12\x41\n\x18stats_for_recent_history\x18\x03 \x01(\x0b\x32\x1f.com.example.monitor.Statistics\x12>\n\x15stats_for_time_bucket\x18\x04 \x01(\x0b\x32\x1f.com.example.monitor.Statistics\"N\n\nStatistics\x12\x0e\n\x06median\x18\x01 \x01(\x02\x12\x0c\n\x04mean\x18\x02 \x01(\x02\x12\r\n\x05stdev\x18\x03 \x01(\x02\x12\x13\n\x0bpredictions\x18\x04 \x03(\x02\x32\x99\x02\n\rDeviceMonitor\x12\x80\x01\n\x0cUpdateMetric\x12#.com.example.monitor.NewMetricValue\x1a\x16.google.protobuf.Empty\"3\x82\xd3\xe4\x93\x02-\"(/deviceMonitors/{device_id}/updateMetric:\x01*\x12\x84\x01\n\x0fGetCurrentValue\x12*.com.example.monitor.GetCurrentMetricValue\x1a .com.example.monitor.MetricValue\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/deviceMonitors/{device_id}b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,cloudstate_dot_entity__key__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_api_dot_http__pb2.DESCRIPTOR,])




_NEWMETRICVALUE = _descriptor.Descriptor(
  name='NewMetricValue',
  full_name='com.example.monitor.NewMetricValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='com.example.monitor.NewMetricValue.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.example.monitor.NewMetricValue.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_value', full_name='com.example.monitor.NewMetricValue.new_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=234,
)


_GETCURRENTMETRICVALUE = _descriptor.Descriptor(
  name='GetCurrentMetricValue',
  full_name='com.example.monitor.GetCurrentMetricValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='com.example.monitor.GetCurrentMetricValue.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=284,
)


_METRICVALUE = _descriptor.Descriptor(
  name='MetricValue',
  full_name='com.example.monitor.MetricValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_value', full_name='com.example.monitor.MetricValue.current_value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prior_value', full_name='com.example.monitor.MetricValue.prior_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats_for_recent_history', full_name='com.example.monitor.MetricValue.stats_for_recent_history', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats_for_time_bucket', full_name='com.example.monitor.MetricValue.stats_for_time_bucket', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=475,
)


_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='com.example.monitor.Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='median', full_name='com.example.monitor.Statistics.median', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean', full_name='com.example.monitor.Statistics.mean', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdev', full_name='com.example.monitor.Statistics.stdev', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predictions', full_name='com.example.monitor.Statistics.predictions', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=555,
)

_METRICVALUE.fields_by_name['stats_for_recent_history'].message_type = _STATISTICS
_METRICVALUE.fields_by_name['stats_for_time_bucket'].message_type = _STATISTICS
DESCRIPTOR.message_types_by_name['NewMetricValue'] = _NEWMETRICVALUE
DESCRIPTOR.message_types_by_name['GetCurrentMetricValue'] = _GETCURRENTMETRICVALUE
DESCRIPTOR.message_types_by_name['MetricValue'] = _METRICVALUE
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewMetricValue = _reflection.GeneratedProtocolMessageType('NewMetricValue', (_message.Message,), dict(
  DESCRIPTOR = _NEWMETRICVALUE,
  __module__ = 'DeviceMonitor_pb2'
  # @@protoc_insertion_point(class_scope:com.example.monitor.NewMetricValue)
  ))
_sym_db.RegisterMessage(NewMetricValue)

GetCurrentMetricValue = _reflection.GeneratedProtocolMessageType('GetCurrentMetricValue', (_message.Message,), dict(
  DESCRIPTOR = _GETCURRENTMETRICVALUE,
  __module__ = 'DeviceMonitor_pb2'
  # @@protoc_insertion_point(class_scope:com.example.monitor.GetCurrentMetricValue)
  ))
_sym_db.RegisterMessage(GetCurrentMetricValue)

MetricValue = _reflection.GeneratedProtocolMessageType('MetricValue', (_message.Message,), dict(
  DESCRIPTOR = _METRICVALUE,
  __module__ = 'DeviceMonitor_pb2'
  # @@protoc_insertion_point(class_scope:com.example.monitor.MetricValue)
  ))
_sym_db.RegisterMessage(MetricValue)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), dict(
  DESCRIPTOR = _STATISTICS,
  __module__ = 'DeviceMonitor_pb2'
  # @@protoc_insertion_point(class_scope:com.example.monitor.Statistics)
  ))
_sym_db.RegisterMessage(Statistics)


_NEWMETRICVALUE.fields_by_name['device_id']._options = None
_GETCURRENTMETRICVALUE.fields_by_name['device_id']._options = None

_DEVICEMONITOR = _descriptor.ServiceDescriptor(
  name='DeviceMonitor',
  full_name='com.example.monitor.DeviceMonitor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=558,
  serialized_end=839,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateMetric',
    full_name='com.example.monitor.DeviceMonitor.UpdateMetric',
    index=0,
    containing_service=None,
    input_type=_NEWMETRICVALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\202\323\344\223\002-\"(/deviceMonitors/{device_id}/updateMetric:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='GetCurrentValue',
    full_name='com.example.monitor.DeviceMonitor.GetCurrentValue',
    index=1,
    containing_service=None,
    input_type=_GETCURRENTMETRICVALUE,
    output_type=_METRICVALUE,
    serialized_options=_b('\202\323\344\223\002\035\022\033/deviceMonitors/{device_id}'),
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICEMONITOR)

DESCRIPTOR.services_by_name['DeviceMonitor'] = _DEVICEMONITOR

# @@protoc_insertion_point(module_scope)
